### ISSUE TITLE
Unsure about the accuracy of the source(s) used for this production

### ISSUE THREAD

**Issue by weijia-cheng** [standardebooks/epictetus_the-enchiridion_elizabeth-carter#4]
I was looking at this production and I am a little uncertain about whether this is actually Elizabeth Carter's translation of the Enchiridion. (Also, if it's not Elizabeth Carter's translation of the Enchiridion, I am not entirely sure whose it is, though I have a guess. I will go into more details later on.)

As it stands this production consists of two things which (as far as I can tell) come from two separate sources: 1) the introduction by George Long, and 2) the body, which is credited to Elizabeth Carter. I think this creates some confusion for the reader because in the introduction, it says "But *I* should not have translated this book ..." and is signed by George Long, but the translation is credited to Elizabeth Carter. I believe that the introduction is taken from [Long's translation of the Discourses and Enchiridion](https://www.gutenberg.org/files/10661/10661-h/10661-h.htm). In fact [Carter's translation](https://www.google.com/books/edition/All_the_works_of_Epictetus_Which_are_now/DVpZAAAAcAAJ?hl=en&gbpv=0) does have an introduction, but it's totally different from the one we have here.

Now that I'm looking at the original text by Carter, that bring me to my second point, that the body isn't actually Carter's translation. For example, the first paragraph of chapter I in Carter's text is:

> Of Things, some are in our Power, and others not. In our Power are Opinion, Pursuit, Desire, Aversion, and in one Word, whatever are our own Actions. Not in our Power, are Body, Property, Reputation, Command, and, in one Word, whatever are not our own Actions.

This is not what we have in our production:

> Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions. Things not in our control are body, property, reputation, command, and, in one word, whatever are not our own actions.

It seems to me that the version on MIT Classics that we based our production on is a much later revision of Carter's translation, as evidenced by the style.

I've tried searching some exact phrases from the MIT version in Google Books and HathiTrust and I couldn't figure out exactly which printed version it corresponds to, but my best guess right now is that it's a slightly revised version of [Higginson's translation](https://archive.org/details/worksofepitetusc00epicrich/page/374/mode/2up) which was itself a more modern revision of Carter's translation. (This would explain why the MIT version is labeled as Carter's translation.)

The Higginson translation is closer to the MIT version, but isn't exactly the same. For example, going back to our first paragraph again, it reads:

> There are things which are within our power, and there are things which are beyond our power. Within our power are opinion, aim, desire, aversion, and, in one word, whatever affairs are our own. Beyond our power are body, property, reputation, office, and, in one word, whatever are not properly our own affairs.

Overall the impression I get is that the Higginson translation and the uncredited MIT translation are very similar in terms of sentence structure but the MIT translation substitutes some words for slightly more contemporary synonyms. This makes me a little unsure about the MIT translation's copyright status, especially since I couldn't match it to anything that appeared in print.

You can do what you'd like with this information but personally I'd suggest that the easiest way to resolve the confusion is just to reproduce this book using the printed version of Higginson's translation, properly credited to him this time. It is a short book with a good [PG transcription](https://www.gutenberg.org/files/45109/45109-h/45109-h.htm) so it would not take too long to produce. I would be willing to work on the redo if you think it would be a useful project.

**Comment by acabal** [comment]
Enchiridion was probably the 1st ebook I made, either that or Princess of Mars. This is also why it exists at all as a standalone ebook, when today we would roll it in to an Epictetus omnibus. At the time  it was made (9ish years ago) there were no scans, which is why none are listed in the ebook. I don't remember where the Long introduction came from.

The MIT translation is credited to Carter and they say on their site everything is PD. I don't think copyright is a problem here.

I'm open to redoing it, and removing the Long introduction, but if we do that we should compile an Epictetus omnibus because he has other short work that would all fit together.  For example here's his complete work by George Long: https://archive.org/details/discoursesepicte00epiciala

Long is always a solid choice for translation. I think Carter also has a complete works translation available somewhere. I think he mostly wrote in fragments so how they're organized is probably a matter of translator's choice.

**Comment by weijia-cheng** [comment]
Ok, so the goal for the redo would be to put the Enchiridion and Fragments translations by Long into their own repository? ("Short Works"? "Works"?) That seems very doable; I can take at it after Proudhon.

**Comment by acabal** [comment]
Right. First you'd have to decide which translation to use. I don't know what to call it - short works implies fiction. I think it'd be best to see what others call the compilation and brainstorm some ideas from there.

**Comment by weijia-cheng** [comment]
Ok, sounds good. I'll post a new thread on the Google Groups once I have an idea of how I want to approach this.
